#!/usr/bin/env python
# coding: utf-8

# In[1]:


import os

# Create directories for your project
project_folder = 'flask_hello_world'
templates_folder = os.path.join(project_folder, 'templates')

os.makedirs(templates_folder, exist_ok=True)

# Create a simple index.html file inside the templates directory
html_content = '''
<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>'''

with open(os.path.join(templates_folder, 'index.html'), 'w') as f:
    f.write(html_content)


# In[2]:


from flask import Flask, render_template
import logging

app = Flask(__name__, template_folder=templates_folder)  # Specify the path to the templates folder
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

@app.route("/")
def hello_world():
    logger.info("Rendering Hello World template")
    return render_template('index.html')


# In[3]:


from threading import Thread

def run_app():
    app.run(port=5001, debug=True, use_reloader=False)  # Change the port if necessary

# Run the Flask application in a separate thread
thread = Thread(target=run_app)
thread.start()


# In[4]:


# Change directory to the root of your project in the Jupyter Notebook environment
os.chdir(project_folder)


# In[5]:


# Run these commands as shell commands within Jupyter Notebook
get_ipython().system('git init')
get_ipython().system('git add .')
get_ipython().system('git commit -m "Initial commit with Flask application"')


# In[7]:


import os
print(os.getcwd())


# In[8]:


get_ipython().system('git --version')


# In[9]:


get_ipython().system('pwd')


# In[14]:


get_ipython().system('git push -u origin main')


# In[ ]:




